### ISSUE TITLE
Create Translation Page

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#142]
※Google 翻訳アプリの、翻訳後の画面レイアウトを参考にする。

- [x] テキストを入力できる。
- [x] 音声入力ボタンで音声入力ができる。
- [x] 発話ボタンで、音声が聞ける。
- [x] 翻訳元テキストを確定すると翻訳ができる。
- [x] 翻訳元言語を変更できる。
- [x] 翻訳先言語を変更できる。
- [x] 翻訳元と翻訳先の言語を入れ替えられる。
- [x] コピーボタンでコピーができる。

**Comment by milkyskies** [comment]
- [ ] Show all locales in the language selector

**Comment by sinproject-iwasaki** [comment]
1/31 完成

**Comment by milkyskies** [comment]
- [ ] Flip text boxes too

**Comment by milkyskies** [comment]
- [ ] Clear button

**Comment by milkyskies** [comment]
- [ ] When text field empty, don't call tts api

**Comment by milkyskies** [comment]
- [ ] When deleting all text from text field, delete text in translation field as well

**Comment by milkyskies** [comment]
- [ ] Speak also when language changed

**Comment by milkyskies** [comment]
- [ ] Change what record button looks like when recording
- [ ] Only allow pressing one speaking button once

**Comment by milkyskies** [comment]
- [ ] When recording audio, don't allow playing audio
- [ ] Don't play audio on flip
- [ ] Don't automatically stop recording audio

**Comment by milkyskies** [comment]
- [ ] Don't play with either are listening
