### ISSUE TITLE
translate: Limit to 250 characters

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#258]
- [x] 250文字まで翻訳できるようにする。
- [x] 251文字以上では、相手のTextAreaに「翻訳できるのは 250文字までです。」と表示する。
- [x] 250文字までデータベースに登録できるようにする。

**Comment by sinproject-iwasaki** [comment]
@milkyskies 
そうですね。DBの方は制限なしでOKです。

**Comment by milkyskies** [comment]
@sinproject-iwasaki 
翻訳されたテキストも、翻訳するテキストと同じValueObjectを使っているため、先ほど言ったDBの問題と同じような問題を予想できます。
２つの解決策を考えています。
1. 翻訳するときとされるときのValueObjectを分ける
2. 文字制限をFrontendで対応する

**Comment by sinproject-iwasaki** [comment]
@milkyskies 

1. 翻訳するときと翻訳されるときのValueObjectを分ける

上記方針で、翻訳するとき用の Value Object を新規に作成して対応してください。
