### ISSUE TITLE
Show progress icon while sending message

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/talk#392]
# 調査

- [x] line: 203: socket.emit('message', *) の、正常完了を検知できるか調査する。
- [x] 対応できれば、 line: 176-179 を削除する。

# 対応

- [x] 送信中は、送信アイコンを、プログレスアイコン（回転する）に変更する。
- [x] 送信完了後に、送信ボタンに戻す。
- [x] 送信完了後に、送信テキストを空文字にする。

**Comment by milkyskies** [comment]
@sinproject-iwasaki 176-169の位置が変わったため削除できません。
